In [1]:
import numpy as np
import generate_HNF
import spglib
from copy import deepcopy
import permutation
import generate_superlattice

rutile = ([(4, 0, 0),(0, 4, 0),(0, 0, 3)],

          [(0, 0, 0),(0.5, 0.5, 0.5),(0.3, 0.3, 0.0),(0.7, 0.7, 0.0),(0.2, 0.8, 0.5),(0.8, 0.2, 0.5)],

          [14, 14, 8, 8, 8, 8])
o_sublattice = ([(4, 0, 0),(0, 4, 0),(0, 0, 3)],

                [(0.3, 0.3, 0.0),(0.7, 0.7, 0.0),(0.2, 0.8, 0.5),(0.8, 0.2, 0.5)],

                [8, 8, 8, 8])
parent_sym = spglib.get_symmetry(rutile)
HNF_list = generate_HNF.generate_all_superlattices(3)
reduced_HNF = generate_HNF.reduce_HNF_list_by_parent_lattice_symmetry(HNF_list, parent_sym["rotations"])

In [2]:
reduced_HNF[2]

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 3]])

In [3]:
parent_lattice = generate_superlattice.get_superlattice(rutile, reduced_HNF[0], 3)
o_sublattice = generate_superlattice.get_o_superlattice(rutile, reduced_HNF[0], 3)
o_sublattice

([[4, 0, 0], [0, 4, 0], [0, 0, 9]],
 [[0.3, 0.3, 0.0],
  [0.7, 0.7, 0.0],
  [0.2, 0.8, 0.1667],
  [0.8, 0.2, 0.1667],
  [0.3, 0.3, 0.3333],
  [0.7, 0.7, 0.3333],
  [0.2, 0.8, 0.5],
  [0.8, 0.2, 0.5],
  [0.3, 0.3, 0.6667],
  [0.7, 0.7, 0.6667],
  [0.2, 0.8, 0.8333],
  [0.8, 0.2, 0.8333]],
 [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [4]:
sym = spglib.get_symmetry(parent_lattice)

並進操作についての置換表現を作る

In [5]:
def trans_gene_per(translation, dic_zahyou):
    """
    対象操作について置換の移り先を示す辞書を作成

    parameters
    
    dic_zahyou 

    retruns

    """
    dic2 = deepcopy(dic_zahyou)
    for l in range(len(dic_zahyou)):
        dic2[l] = (dic_zahyou[l] + translation) % 1
    tin = dict()
    for l in range(len(dic_zahyou)):
        for j in range(len(dic_zahyou)):
            if all(np.round(dic_zahyou[j], 4) == np.round(dic2[l], 4)):
                tin[l] = j
    return tin

def generate_per2(superlattice, o_sublattice):##各座標をnumpyに変換して、gene_perを使う
    parent_sym = spglib.get_symmetry(superlattice)
    tin = dict()
    arr = np.asarray(o_sublattice[1])   #lattcie no 行列表示
    dic = dict()                        #分率座標の行列表示
    for i in range(len(o_sublattice[1])):
        dic[i] = np.asarray(o_sublattice[1][i])

    jun = dict()
    for i in range(len(parent_sym["translations"])):
        jun[i] = gene_per(parent_sym["rotations"][i], parent_sym["translations"][i], dic)
    return jun

In [6]:
index = 3
dimention = index
npdata = np.zeros((3,index))

In [7]:
arr = np.asarray(o_sublattice[1])   #lattcie no 行列表示
dic = dict()                        #分率座標の行列表示
for i in range(len(o_sublattice[1])):
    dic[i] = np.asarray(o_sublattice[1][i])

In [8]:
parent_lattice_jun = permutation.generate_per(parent_lattice, o_sublattice)

for jack in range(5):
    print("今はi = ", jack)
    a = list()
    parent_lattice = unko.get_superlattice(rutile, reduced_HNF[jack], 2)
    o_sublattice = unko.get_o_superlattice(rutile, reduced_HNF[jack], 2)
    parent_lattice_jun = permutation.generate_per(parent_lattice, o_sublattice)
    for ken in range(8):
        can = permutation.make_candidate(o_sublattice, ken)
        auncko = permutation.unique(o_sublattice, parent_lattice_jun, can)
        a.extend(auncko)
    print(a)

In [9]:
sample_HNF = np.array([[2, 0, 0],
       [0, 1, 0],
       [1, 1, 3]])

In [10]:
sample_HNF

array([[2, 0, 0],
       [0, 1, 0],
       [1, 1, 3]])

numpy配列同士の結合

In [11]:
a = np.array([2, 0, 0])
b = np.array([2, 1, 0])
a = np.vstack((a, b))
a

array([[2, 0, 0],
       [2, 1, 0]])

実際に関数を作る

In [12]:
def gene_trans(HNF):
    int_HNF = HNF.astype('int64')
    vectors = np.zeros(3)
    hantei = True
    for dimention in range(3):
        cp_vecs = deepcopy(vectors)
        if HNF[dimention][dimention] > 1:
            for king in range(1, HNF[dimention][dimention]):
                cp_vecs2 = deepcopy(cp_vecs)
                if hantei:
                    cp_vecs2[dimention] += king/HNF[dimention][dimention]
                else:
                    for num_vecs in range(cp_vecs2.shape[0]):
                        cp_vecs2[num_vecs][dimention] += king/HNF[dimention][dimention]
                vectors = np.vstack((vectors, cp_vecs2))
            hantei = False
    return vectors       

In [13]:
sample_HNF = np.array([[2, 0, 0],
       [0, 1, 0],
       [1, 1, 3]])
ta = gene_trans(sample_HNF)
ta

array([[0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.33333333],
       [0.5       , 0.        , 0.33333333],
       [0.        , 0.        , 0.66666667],
       [0.5       , 0.        , 0.66666667]])

並進操作の置換表現を得る

In [14]:
def get_trans_permuation(dic_zahyou, translation):
    tin = dict()
    dic2 = deepcopy(dic_zahyou)
    for l in range(len(dic_zahyou)):
        dic2[l] = (dic_zahyou[l] + translation)
        dic2[l] = np.round(dic2[l], 3)%1
    for l in range(len(dic_zahyou)):
        for j in range(len(dic_zahyou)):
            if all(np.round(dic_zahyou[j], 3) == np.round(dic2[l], 3)):
                tin[l] = j
    return tin

In [15]:
dic_zahyou = dict()                        #分率座標の行列表示
for i in range(len(o_sublattice[1])):
    dic_zahyou[i] = np.asarray(o_sublattice[1][i])
dic_zahyou

{0: array([0.3, 0.3, 0. ]),
 1: array([0.7, 0.7, 0. ]),
 2: array([0.2   , 0.8   , 0.1667]),
 3: array([0.8   , 0.2   , 0.1667]),
 4: array([0.3   , 0.3   , 0.3333]),
 5: array([0.7   , 0.7   , 0.3333]),
 6: array([0.2, 0.8, 0.5]),
 7: array([0.8, 0.2, 0.5]),
 8: array([0.3   , 0.3   , 0.6667]),
 9: array([0.7   , 0.7   , 0.6667]),
 10: array([0.2   , 0.8   , 0.8333]),
 11: array([0.8   , 0.2   , 0.8333])}

In [16]:
translations = gene_trans(reduced_HNF[0])
tan = get_trans_permuation(dic_zahyou, translations[2])
tan

{0: 8, 1: 9, 2: 10, 3: 11, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6, 11: 7}

In [17]:
def get_trans_perms(dic_zahyou, translations):
    trans_perms = dict()
    for i in range(len(translations)):
        trans_perms[i] = get_trans_permuation(dic_zahyou, translations[i])
    return trans_perms

In [18]:
hama = get_trans_perms(dic_zahyou, translations)
hama

{0: {0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11},
 1: {0: 4,
  1: 5,
  2: 6,
  3: 7,
  4: 8,
  5: 9,
  6: 10,
  7: 11,
  8: 0,
  9: 1,
  10: 2,
  11: 3},
 2: {0: 8,
  1: 9,
  2: 10,
  3: 11,
  4: 0,
  5: 1,
  6: 2,
  7: 3,
  8: 4,
  9: 5,
  10: 6,
  11: 7}}

並進操作と回転操作を組み合わせる

In [19]:
def kumiawase(rot_tikan, trans_tikan):
    hosii = dict()
    for i in range(len(rot_tikan)):
        hosii[i] = trans_tikan[rot_tikan[i]]
    return hosii

In [20]:
parent_lattice_jun[0]

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11}

In [21]:
hama[2]

{0: 8, 1: 9, 2: 10, 3: 11, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6, 11: 7}

In [22]:
tani = kumiawase(parent_lattice_jun[0], hama[2])
tani

{0: 8, 1: 9, 2: 10, 3: 11, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6, 11: 7}

回転操作の置換の辞書と並進操作の置換の辞書から最終形の辞書を作る

In [23]:
def generate_abs_permuatation(parent_lattice_jun, trans_perms):
    tikan_list = list()
    for i in parent_lattice_jun:
        for j in trans_perms:
            if i == 1:
                print(j, trans_perms[j])
            tikan = kumiawase(parent_lattice_jun[i], trans_perms[j])
            if i == 1:
                print(tikan)
            tikan_list.append(tikan)
    return tikan_list

In [24]:
tera = generate_abs_permuatation(parent_lattice_jun, hama)
tera

0 {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11}
{0: 1, 1: 0, 2: 11, 3: 10, 4: 9, 5: 8, 6: 7, 7: 6, 8: 5, 9: 4, 10: 3, 11: 2}
1 {0: 4, 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 0, 9: 1, 10: 2, 11: 3}
{0: 5, 1: 4, 2: 3, 3: 2, 4: 1, 5: 0, 6: 11, 7: 10, 8: 9, 9: 8, 10: 7, 11: 6}
2 {0: 8, 1: 9, 2: 10, 3: 11, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6, 11: 7}
{0: 9, 1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1, 9: 0, 10: 11, 11: 10}


[{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11},
 {0: 4, 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 0, 9: 1, 10: 2, 11: 3},
 {0: 8, 1: 9, 2: 10, 3: 11, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6, 11: 7},
 {0: 1, 1: 0, 2: 11, 3: 10, 4: 9, 5: 8, 6: 7, 7: 6, 8: 5, 9: 4, 10: 3, 11: 2},
 {0: 5, 1: 4, 2: 3, 3: 2, 4: 1, 5: 0, 6: 11, 7: 10, 8: 9, 9: 8, 10: 7, 11: 6},
 {0: 9, 1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1, 9: 0, 10: 11, 11: 10},
 {0: 6, 1: 7, 2: 9, 3: 8, 4: 10, 5: 11, 6: 1, 7: 0, 8: 2, 9: 3, 10: 5, 11: 4},
 {0: 10, 1: 11, 2: 1, 3: 0, 4: 2, 5: 3, 6: 5, 7: 4, 8: 6, 9: 7, 10: 9, 11: 8},
 {0: 2, 1: 3, 2: 5, 3: 4, 4: 6, 5: 7, 6: 9, 7: 8, 8: 10, 9: 11, 10: 1, 11: 0},
 {0: 7, 1: 6, 2: 4, 3: 5, 4: 3, 5: 2, 6: 0, 7: 1, 8: 11, 9: 10, 10: 8, 11: 9},
 {0: 11, 1: 10, 2: 8, 3: 9, 4: 7, 5: 6, 6: 4, 7: 5, 8: 3, 9: 2, 10: 0, 11: 1},
 {0: 3, 1: 2, 2: 0, 3: 1, 4: 11, 5: 10, 6: 8, 7: 9, 8: 7, 9: 6, 10: 4, 11: 5},
 {0: 1, 1: 0, 2: 3, 3: 2, 4: 5, 5: 4, 6: 7, 7: 6, 8:

In [25]:
def make_candidate(o_sublattice, l):
    omomi4 = []
    for i in range(2**len(o_sublattice[2])):
        k = format(i,'b').zfill(len(o_sublattice[2]))
        sum = 0
        for m in range(len(k)):
            sum += int(k[m])
        if sum ==l :
            omomi4.append(k)
    return omomi4

def unique(parent_sym_jun, omomi4):
    """
    対象操作について置換の移り先を示す辞書を作成

    parameters
    
    parent_sym_jun
    
    omomi4 は各空孔数ごとのcandidate集合

    retruns

    """
    omomi4_neo = deepcopy(omomi4)#copy wo sakusei
    lis = set()

    for i in range(len(omomi4)):#through all candidate
        if omomi4[i] in omomi4_neo:#kouho ga mada 生き残ってるかチェック
            for j in range(1, len(parent_sym_jun[0])):#置換操作について回す　
                d = dict()
                sta = ""
                for k in range(len(parent_sym_jun[0])):
                    d[parent_sym_jun[j][k]] = omomi4[i][k]#str辞書の作成
                for r  in range(len(parent_sym_jun[0])):#staの作成 sta is made from tikan[j]
                    sta += d[r]
                    if sta in omomi4_neo:
                        omomi4_neo.remove(sta)
                        lis.add(omomi4[i])
    
    return lis

In [26]:
omomi4 = make_candidate(o_sublattice, 4)

In [27]:
jack = unique(tera, omomi4)
jack

{'000000001111',
 '000000010111',
 '000000011011',
 '000000011101',
 '000000011110',
 '000000100111',
 '000000101011',
 '000000101101',
 '000000110011',
 '000001000111',
 '000001001011',
 '000001001101',
 '000001001110',
 '000001010011',
 '000001010101',
 '000001010110',
 '000001011001',
 '000001011010',
 '000001100011',
 '000001100101',
 '000001101001',
 '000001110001',
 '000010000111',
 '000010001011',
 '000010001101',
 '000010001110',
 '000010010011',
 '000010010101',
 '000010011001',
 '000010011010',
 '000010100011',
 '000010100101',
 '000010101001',
 '000010101010',
 '000011000011',
 '000100010011',
 '000100010101',
 '000100010110',
 '000100011001',
 '000100011010',
 '000100100011',
 '000100100101',
 '000100100110',
 '000100101001',
 '000100101010',
 '000100110010',
 '000101000101',
 '000101000110',
 '000101001010',
 '000110000101',
 '000110000110',
 '001001000101',
 '001010000101'}