In [1]:
import numpy as np
import generate_HNF
import spglib
from copy import deepcopy
import permutation
import generate_superlattice

rutile = ([(4, 0, 0),

           (0, 4, 0),

           (0, 0, 3)],

          [(0, 0, 0),

           (0.5, 0.5, 0.5),

           (0.3, 0.3, 0.0),

           (0.7, 0.7, 0.0),

           (0.2, 0.8, 0.5),

           (0.8, 0.2, 0.5)],

          [14, 14, 8, 8, 8, 8])
o_sublattice = ([(4, 0, 0),

                 (0, 4, 0),

                 (0, 0, 3)],

                [(0.3, 0.3, 0.0),

                 (0.7, 0.7, 0.0),

                 (0.2, 0.8, 0.5),

                 (0.8, 0.2, 0.5)],

                [8, 8, 8, 8])
parent_sym = spglib.get_symmetry(rutile)
HNF_list = generate_HNF.generate_all_superlattices(3)
reduced_HNF = generate_HNF.reduce_HNF_list_by_parent_lattice_symmetry(
    HNF_list, parent_sym["rotations"])

In [2]:
reduced_HNF

[array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 3]]), array([[1, 0, 0],
        [0, 1, 0],
        [0, 1, 3]]), array([[1, 0, 0],
        [0, 1, 0],
        [1, 1, 3]]), array([[1, 0, 0],
        [0, 3, 0],
        [0, 0, 1]]), array([[1, 0, 0],
        [1, 3, 0],
        [0, 0, 1]])]

ある対称操作がMに属すのか判定

In [3]:
# reduced_HNF[0]について
H = reduced_HNF[0]
H_inv = np.linalg.inv(H)
for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    check_det = np.linalg.det(check)
    print(i, check_det)

0 1.0
1 -1.0
2 1.0
3 -1.0
4 1.0
5 -1.0
6 1.0
7 -1.0
8 1.0
9 -1.0
10 1.0
11 -1.0
12 1.0
13 -1.0
14 1.0
15 -1.0


In [4]:
# reduced_HNF[1]について
H = reduced_HNF[1]
H_inv = np.linalg.inv(H)

def is_unimodular(M: np.ndarray) -> bool:

    if np.abs(np.around(np.linalg.det(M))) == 1:

        return True

    else:

        return False
def cast_integer_matrix(arr: np.ndarray) -> np.ndarray:

    arr_int = np.around(arr).astype(np.int)

    return arr_int
    
for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    check_det = np.linalg.det(check)
    a = cast_integer_matrix(check)
    b = np.isclose(check, a)
    print(i , a,b)

0 [[1 0 0]
 [0 1 0]
 [0 0 1]] [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
1 [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]] [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
2 [[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]] [[ True  True  True]
 [ True  True  True]
 [False False  True]]
3 [[ 0  1  0]
 [-1  0  0]
 [ 0  0 -1]] [[ True  True  True]
 [ True  True  True]
 [False False  True]]
4 [[-1  0  0]
 [ 0 -1  0]
 [ 0  1  1]] [[ True  True  True]
 [ True  True  True]
 [ True False  True]]
5 [[ 1  0  0]
 [ 0  1  0]
 [ 0 -1 -1]] [[ True  True  True]
 [ True  True  True]
 [ True False  True]]
6 [[ 0  1  0]
 [-1  0  0]
 [ 0  0  1]] [[ True  True  True]
 [ True  True  True]
 [False False  True]]
7 [[ 0 -1  0]
 [ 1  0  0]
 [ 0  0 -1]] [[ True  True  True]
 [ True  True  True]
 [False False  True]]
8 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]] [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
9 [[-1  0  0]
 [ 0  1  0]
 [ 0  0  1]] [[ True  True  True]
 [ True  True  True]
 

In [5]:
check = H_inv.dot(parent_sym["rotations"][2].dot(H))
check

array([[ 0.        , -1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  0.33333333,  1.        ]])

In [14]:
def is_integer_matrix(matrix):
    a = True
    for i in range(0, 3):
        for j in range(0, 3):
            if not matrix[i][j].is_integer():
                a = False
                break
    return a

In [17]:
# reduced_HNF[1]について
H = reduced_HNF[1]
H_inv = np.linalg.inv(H)

for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    if is_integer_matrix(check):
        print(check)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
# reduced_HNF[0]について
H = reduced_HNF[0]
H_inv = np.linalg.inv(H)

for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    if is_integer_matrix(check):
        print(check)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]


In [19]:
# reduced_HNF[2]について
H = reduced_HNF[2]
H_inv = np.linalg.inv(H)

for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    if is_integer_matrix(check):
        print(check)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [20]:
# reduced_HNF[3]について
H = reduced_HNF[3]
H_inv = np.linalg.inv(H)

for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    if is_integer_matrix(check):
        print(check)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


In [21]:
# reduced_HNF[4]について
H = reduced_HNF[4]
H_inv = np.linalg.inv(H)

for i in range(len(parent_sym["rotations"])):
    check = H_inv.dot(parent_sym["rotations"][i].dot(H))
    if is_integer_matrix(check):
        print(check)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[-1. -3.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
[[ 1.  3.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 1.  3.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
[[-1. -3.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [28]:
i = 4
parent_lattice = generate_superlattice.get_superlattice(rutile, reduced_HNF[i], 3)
o_sublattice = generate_superlattice.get_o_superlattice(rutile, reduced_HNF[i], 3)
sym3 = spglib.get_symmetry(parent_lattice)
sym3

{'rotations': array([[[ 1,  0,  0],
         [ 0,  1,  0],
         [ 0,  0,  1]],
 
        [[-1,  0,  0],
         [ 0, -1,  0],
         [ 0,  0, -1]],
 
        [[-1,  0,  0],
         [ 0, -1,  0],
         [ 0,  0,  1]],
 
        [[ 1,  0,  0],
         [ 0,  1,  0],
         [ 0,  0, -1]]], dtype=int32), 'translations': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), 'equivalent_atoms': array([ 0,  1,  2,  3,  2,  3,  6,  6,  8,  9, 10, 11, 12, 10,  9, 12, 11,
         8], dtype=int32)}

In [12]:
np.isclose(reduced_HNF[0], reduced_HNF[1] )

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])