In [1]:
import numpy as np
import generate_HNF
import spglib
from copy import deepcopy
import permutation
import generate_superlattice

rutile = ([(4, 0, 0),

           (0, 4, 0),

           (0, 0, 3)],

          [(0, 0, 0),

           (0.5, 0.5, 0.5),

           (0.3, 0.3, 0.0),

           (0.7, 0.7, 0.0),

           (0.2, 0.8, 0.5),

           (0.8, 0.2, 0.5)],

          [14, 14, 8, 8, 8, 8])
o_sublattice = ([(4, 0, 0),

           (0, 4, 0),

           (0, 0, 3)],

          [(0.3, 0.3, 0.0),

           (0.7, 0.7, 0.0),

           (0.2, 0.8, 0.5),

           (0.8, 0.2, 0.5)],

          [8, 8, 8, 8])
parent_sym = spglib.get_symmetry(rutile)
HNF_list = generate_HNF.generate_all_superlattices(2)
reduced_HNF = generate_HNF.reduce_HNF_list_by_parent_lattice_symmetry(HNF_list, parent_sym["rotations"])

In [2]:
superlattice = generate_superlattice.get_superlattice(rutile, reduced_HNF[0], 2)
superlattice

([[4, 0, 0], [0, 4, 0], [0, 0, 6]],
 [[0.0, 0.0, 0.0],
  [0.5, 0.5, 0.25],
  [0.3, 0.3, 0.0],
  [0.7, 0.7, 0.0],
  [0.2, 0.8, 0.25],
  [0.8, 0.2, 0.25],
  [0.0, 0.0, 0.5],
  [0.5, 0.5, 0.75],
  [0.3, 0.3, 0.5],
  [0.7, 0.7, 0.5],
  [0.2, 0.8, 0.75],
  [0.8, 0.2, 0.75]],
 [14, 14, 14, 14, 8, 8, 8, 8, 8, 8, 8, 8])

In [3]:
def tukuru(o_sublattice, HNF):  #need repair#########################################################################
    a = np.sum(HNF, axis=1)
    def zurasu(vector, motono):
        t = deepcopy(motono)
        for i in range(len(motono)):
            t[i] += vector
        d = np.concatenate([motono,t])
        return d
    # Sn についてまずはずらす
    Sn_sublattice = [(0, 0, 0), (0.5, 0.5, 0.5)]
    new_Sn_zahyou = deepcopy(Sn_sublattice)
    for i in range(3):
        for j in range(1, a[i]):# a[i]が整数行列でないとエラーを起こす。　dtype=np.int で解決
            vec = np.zeros(3)
            vec[i] = j
            concat = deepcopy(Sn_sublattice)
            for i in range(2):
                concat[i] += vec
            new_Sn_zahyou = np.concatenate(new_Sn_zahyou, concat)
    new_O_zahyou = deepcopy(o_sublattice[1])
    for i in range(3):
        for j in range(1, a[i]):# a[i]が整数行列でないとエラーを起こす。　dtype=np.int で解決
            vec = np.zeros(3)
            vec[i] = j
            new_O_zahyou = zurasu(vec, new_O_zahyou)
    return new_Sn_zahyou
    

In [4]:
a = tukuru(rutile, reduced_HNF[2])
a

TypeError: 'list' object cannot be interpreted as an integer

In [5]:
reduced_HNF

[array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 2]]), array([[1, 0, 0],
        [0, 1, 0],
        [0, 1, 2]]), array([[1, 0, 0],
        [0, 1, 0],
        [1, 1, 2]]), array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 1]]), array([[1, 0, 0],
        [1, 2, 0],
        [0, 0, 1]])]

In [6]:
a = np.sum(reduced_HNF[4], axis=1)
a

array([1, 3, 1])

In [7]:
 # Sn についてまずはずらす
Sn_sublattice = [(0, 0, 0), (0.5, 0.5, 0.5)]
new_Sn_zahyou = deepcopy(Sn_sublattice)
for i in range(3):
    for j in range(1, a[i]):# a[i]が整数行列でないとエラーを起こす。　dtype=np.int で解決
        vec = np.zeros(3)
        vec[i] = j
        concat = deepcopy(Sn_sublattice)
        

In [8]:
def zurasu(vector, motono):
    t = deepcopy(motono)
    for i in range(len(motono)):
        t[i] += vector
        d = np.concatenate([motono,t])
    return d
Sn_sublattice = [(0, 0, 0), (0.5, 0.5, 0.5)]
vec = np.asarray([1, 0, 0])
h = zurasu(vec, Sn_sublattice)
for j in range(1, a[i]):
    vec = np.zeros(3)
    vec[i] = j
    for k in range(motono):
        t[i] += vector
    d = np.concatenate([motono, t])

In [9]:
a = [1, 2, 3]
motono = [(0, 0, 0), (0.5, 0.5, 0.5)]
original = deepcopy(motono)
for j in range(1, a[2]):
    vec = np.zeros(3)
    vec[i] = j
    t = deepcopy(original)
    for k in range(len(original)):
        t[k] += vec
    motono = np.concatenate([motono, t])

In [10]:
motono

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 0. , 1. ],
       [0.5, 0.5, 1.5],
       [0. , 0. , 2. ],
       [0.5, 0.5, 2.5]])

In [11]:
def zurasu(motono, a, i):
    original = deepcopy(motono)
    for j in range(1, a[i]):
        vec = np.zeros(3)
        vec[i] = j
        t = deepcopy(original)
        for k in range(len(original)):
            t[k] += vec
        motono = np.concatenate([motono, t])
    return motono

In [22]:
a = [1, 2, 3]
motono = [(0, 0, 0), (0.5, 0.5, 0.5)]
c = zurasu(motono, a, 2)
c

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 0. , 1. ],
       [0.5, 0.5, 1.5],
       [0. , 0. , 2. ],
       [0.5, 0.5, 2.5]])

In [14]:
def tukuru(lattice, HNF): 
    a = np.sum(HNF, axis=1)
    for i in range(3):
        lattice = zurasu(lattice, a, i)
    return lattice  

In [15]:
Sn_sublattice = [(0, 0, 0), (0.5, 0.5, 0.5)]
a = tukuru(Sn_sublattice, reduced_HNF[2])
a

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 0. , 1. ],
       [0.5, 0.5, 1.5],
       [0. , 0. , 2. ],
       [0.5, 0.5, 2.5],
       [0. , 0. , 3. ],
       [0.5, 0.5, 3.5]])

In [16]:
def making_superlattice(HNF):
    Sn_sublattice = [(0, 0, 0), (0.5, 0.5, 0.5)]
    O_sublattice =  [(0.3, 0.3, 0.0),(0.7, 0.7, 0.0),(0.2, 0.8, 0.5),(0.8, 0.2, 0.5)]
    Sn_superlattice = tukuru(Sn_sublattice, HNF)
    O_superlattice = tukuru(O_sublattice, HNF)
    superlattice = np.concatenate([Sn_superlattice, O_superlattice])
    
    g = deepcopy(superlattice)
    renew = np.linalg.inv(HNF)#逆行列 新しいsuperlatticevector で分立座標にあらわせるように　
    renew = renew.T
    for i in range(len(superlattice)):
        g[i] = g[i].dot(renew)
    
    #消すべき行を記録
    h = []
    for kesu in range(len(g)):
        if  0 <= g[kesu][0] < 1 and 0 <= g[kesu][1] < 1 and 0 <= g[kesu][2] < 1 :
            continue
        else:
            h.append(kesu)
        
    new_zahyou = np.delete(g, h, 0)
    return new_zahyou
        
    

In [17]:
making_superlattice(reduced_HNF[2])

array([[0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 ],
       [0.5 , 0.5 , 0.25],
       [0.5 , 0.5 , 0.75],
       [0.3 , 0.3 , 0.2 ],
       [0.2 , 0.8 , 0.25],
       [0.8 , 0.2 , 0.25],
       [0.3 , 0.3 , 0.7 ],
       [0.7 , 0.7 , 0.3 ],
       [0.2 , 0.8 , 0.75],
       [0.8 , 0.2 , 0.75],
       [0.7 , 0.7 , 0.8 ]])

In [18]:
import unko
a = unko.get_superlattice(rutile, reduced_HNF[2], 2)

In [19]:
a

([[4, 0, 0], [0, 4, 0], [4, 4, 6]],
 [[0.0, 0.0, 0.0],
  [0.0, 0.0, 0.5],
  [0.5, 0.5, 0.25],
  [0.5, 0.5, 0.75],
  [0.3, 0.3, 0.2],
  [0.2, 0.8, 0.25],
  [0.8, 0.2, 0.25],
  [0.3, 0.3, 0.7],
  [0.7, 0.7, 0.3],
  [0.2, 0.8, 0.75],
  [0.8, 0.2, 0.75],
  [0.7, 0.7, 0.8]],
 [32, 32, 32, 32, 16, 16, 16, 16, 16, 16, 16, 16])

In [20]:
su = spglib.get_symmetry(a)