index2 でうまくいくのか試験

In [1]:
import numpy as np
import generate_HNF
import spglib
from copy import deepcopy
import permutation
import generate_superlattice
import unko

rutile = ([(4, 0, 0),

           (0, 4, 0),

           (0, 0, 3)],

          [(0, 0, 0),

           (0.5, 0.5, 0.5),

           (0.3, 0.3, 0.0),

           (0.7, 0.7, 0.0),

           (0.2, 0.8, 0.5),

           (0.8, 0.2, 0.5)],

          [14, 14, 8, 8, 8, 8])
o_sublattice = ([(4, 0, 0),

                 (0, 4, 0),

                 (0, 0, 3)],

                [(0.3, 0.3, 0.0),

                 (0.7, 0.7, 0.0),

                 (0.2, 0.8, 0.5),

                 (0.8, 0.2, 0.5)],

                [8, 8, 8, 8])
parent_sym = spglib.get_symmetry(rutile)
HNF_list = generate_HNF.generate_all_superlattices(2)
reduced_HNF = generate_HNF.reduce_HNF_list_by_parent_lattice_symmetry(
    HNF_list, parent_sym["rotations"])

In [8]:
parent_lattice = unko.get_superlattice(rutile, reduced_HNF[2], 2)
o_sublattice = unko.get_o_superlattice(rutile, reduced_HNF[2], 2)
print(parent_lattice)
sun = spglib.get_symmetry(parent_lattice)
print(len(sun["rotations"]))
for y in range(32):
    print(y,  sun["rotations"][y], sun["translations"][y])

([[4, 0, 3], [0, 4, 3], [0, 0, 6]], [[0.0, 0.0, 0.0], [0.0, 0.0, 0.5], [0.5, 0.5, 0.25], [0.5, 0.5, 0.75], [0.3, 0.3, 0.2], [0.2, 0.8, 0.25], [0.8, 0.2, 0.25], [0.3, 0.3, 0.7], [0.7, 0.7, 0.3], [0.2, 0.8, 0.75], [0.8, 0.2, 0.75], [0.7, 0.7, 0.8]], [50, 50, 50, 50, 8, 8, 8, 8, 8, 8, 8, 8])
32
0 [[1 0 0]
 [0 1 0]
 [0 0 1]] [0. 0. 0.]
1 [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]] [0. 0. 0.]
2 [[ 0 -1  0]
 [ 1  0  0]
 [ 0  1  1]] [0.5  0.5  0.75]
3 [[ 0  1  0]
 [-1  0  0]
 [ 0 -1 -1]] [0.5  0.5  0.75]
4 [[-1  0  0]
 [ 0 -1  0]
 [ 1  1  1]] [0. 0. 0.]
5 [[ 1  0  0]
 [ 0  1  0]
 [-1 -1 -1]] [0. 0. 0.]
6 [[ 0  1  0]
 [-1  0  0]
 [ 1  0  1]] [0.5  0.5  0.75]
7 [[ 0 -1  0]
 [ 1  0  0]
 [-1  0 -1]] [0.5  0.5  0.75]
8 [[ 1  0  0]
 [ 0 -1  0]
 [-1  0 -1]] [0.5  0.5  0.75]
9 [[-1  0  0]
 [ 0  1  0]
 [ 1  0  1]] [0.5  0.5  0.75]
10 [[ 0 -1  0]
 [-1  0  0]
 [ 0  0 -1]] [0. 0. 0.]
11 [[0 1 0]
 [1 0 0]
 [0 0 1]] [0. 0. 0.]
12 [[-1  0  0]
 [ 0  1  0]
 [ 0 -1 -1]] [0.5  0.5  0.75]
13 [[ 1  0  0]
 [ 0 -1  0]
 [ 

In [3]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

In [4]:
for jack in range(5):
    print("今はi = ", jack)
    a = list()
    parent_lattice = unko.get_superlattice(rutile, reduced_HNF[jack], 2)
    o_sublattice = unko.get_o_superlattice(rutile, reduced_HNF[jack], 2)
    parent_lattice_jun = permutation.generate_per(parent_lattice, o_sublattice)
    for ken in range(8):
        can = permutation.make_candidate(o_sublattice, ken)
        auncko = permutation.unique(o_sublattice, parent_lattice_jun, can)
        a.extend(auncko)
    if jack == 2:
        print(a)

今はi =  0
今はi =  1
今はi =  2
['00000001', '00000011', '00000110', '00001001', '00000111', '00001011', '00010011', '00011001', '00001111', '00010111', '00011011', '00011110', '00101011', '00101101', '00110101', '00011111', '00101111', '00110111', '01100111', '00111111', '01101111', '01111110', '01111111']
今はi =  3
今はi =  4


In [6]:
import numpy as np
import pymatgen
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core import Lattice, Structure
from pymatgen.core.periodic_table import DummySpecie
from pymatgen.io.cif import CifWriter
sga = SpacegroupAnalyzer(o_sublattice, symprec=1e-6, angle_tolerance=1e-2)
struct = sga.get_primitive_standard_structure()
struct

AttributeError: 'tuple' object has no attribute 'lattice'

In [38]:

import os


from pymatgen.io.cif import CifWriter
from pymatgen.io.cif import CifParser
from pymatgen.core import Specie, DummySpecie
from pymatgen.core import Lattice, Structure


def write_cif(filename, struct, refine_cell=False, resize_volume=False):

    cw = CifWriter(struct)

    cw.write_file(filename)

In [35]:
latt = Lattice(o_sublattice[0])
latt

Lattice
    abc : 5.656854249492381 8.0 3.0
 angles : 90.0 90.0 45.00000000000001
 volume : 96.0
      A : 4.0 4.0 0.0
      B : 0.0 8.0 0.0
      C : 0.0 0.0 3.0

In [36]:
[DummySpecie('X')]

[DummySpecie X0+]

In [37]:
struct = Structure(o_sublattice[0],o_sublattice[2], o_sublattice[1])
struct.to(filename="tin.cif")

In [33]:
ls

916仕切り直し.ipynb       O_sublattice919.ipynb  unko.py
920.ipynb                 permutation.py         Untitled.ipynb
generate_HNF.py           POSCAR                 utils.py
generate_superlattice.py  __pycache__/           物質情報工学＿過大.ipynb
hello_world.py            README.md              確認.ipynb
__init__.py               taishousousa919.ipynb
matome922.ipynb           tin.cif


In [9]:
def get_structure(filename):

    cp = CifParser(filename)

    structure = cp.get_structures(primitive=True)[0]

    return structure

In [10]:
rutile = get_structure('/home/asa/dsenum/dsenum/examples/TiO2_mp-2657_conventional_standard.cif')

In [11]:
rutile

Structure Summary
Lattice
    abc : 2.96920288 4.65327231 4.65327231
 angles : 90.0 90.0 90.0
 volume : 64.29198128323142
      A : -0.0 -0.0 2.96920288
      B : 4.65327231 -0.0 2.849307520001255e-16
      C : 7.483032596824123e-16 4.65327231 2.849307520001255e-16
PeriodicSite: Ti (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: Ti (2.3266, 2.3266, 1.4846) [0.5000, 0.5000, 0.5000]
PeriodicSite: O (0.9093, 3.7439, 1.4846) [0.5000, 0.1954, 0.8046]
PeriodicSite: O (3.7439, 0.9093, 1.4846) [0.5000, 0.8046, 0.1954]
PeriodicSite: O (3.2360, 3.2360, 0.0000) [0.0000, 0.6954, 0.6954]
PeriodicSite: O (1.4173, 1.4173, 0.0000) [0.0000, 0.3046, 0.3046]

In [12]:
rutile.to(fmt="poscar")
rutile.to(filename="POSCAR")

In [13]:
ls

916仕切り直し.ipynb       matome922.ipynb        taishousousa919.ipynb
920.ipynb                 O_sublattice919.ipynb  unko.py
generate_HNF.py           permutation.py         Untitled.ipynb
generate_superlattice.py  POSCAR                 utils.py
hello_world.py            __pycache__/           物質情報工学＿過大.ipynb
__init__.py               README.md              確認.ipynb


In [14]:
o_sublattice

([[4, 4, 0], [0, 8, 0], [0, 0, 3]],
 [[0.3, 0.0, 0.0],
  [0.7, 0.0, 0.0],
  [0.2, 0.3, 0.5],
  [0.3, 0.5, 0.0],
  [0.7, 0.5, 0.0],
  [0.2, 0.8, 0.5],
  [0.8, 0.2, 0.5],
  [0.8, 0.7, 0.5]],
 [16, 16, 16, 16, 16, 16, 16, 16])

In [40]:
index = 2
name = 'SnOx_index={}'.format(index)
filename = os.path.join('examples', name, "SnOx_index={}_{}.cif".format(index, 42))
write_cif(filename, struct, refine_cell=True)

FileNotFoundError: [Errno 2] No such file or directory: 'examples/SnOx_index=2/SnOx_index=2_42.cif'